# @url = https://inventario-fonseca.herokuapp.com
@url = http://localhost:4000

###get bodegas
GET {{url}}/bodegas

###get single bodega
GET {{url}}/bodegas/621334dc67b45994295ae977

###create bodega
POST {{url}}/bodegas
Content-Type: application/json

{
  "identificador": "BO005",
  "nombre": "Bodega extranjera",
  "direccion": "Muy lejos"
}

###update bodega
PUT {{url}}/bodegas/6213dbc0f25ba4f4df020ca0
Content-Type: application/json

{ 
  "identificador": "BO001",
  "nombre": "Bodega mayor",
  "direccion": "Calle 1 no. 2-3"
}

###delete bodega
DELETE {{url}}/bodegas/621334dc67b45994295ae977


//apis a bodegas_articulos

###get bodegas_articulos
GET {{url}}/bodegas_articulos

###get articulos de bodega
GET {{url}}/bodegas_articulos/621422b59eb4d8491ac77237

###create bodega_articulo
POST {{url}}/bodegas_articulos
Content-Type: application/json

{
  "id_bodega": "621422b59eb4d8491ac77237",
  "id_articulo": "6215508a3d3b916dd0f7a8b8",
  "cantidad": 10
}

###update bodega_artic
PUT {{url}}/bodegas_articulos/6213b9e64a235020894cc928
Content-Type: application/json

{
  "cantidad": 999
}

###delete bodega
DELETE {{url}}/bodegas_articulos/6213b9e64a235020894cc928
